version: '3.1'
services:
  app:
    container_name: springboot-postgresql
    image: scalde44/spring-pg:v2
    build: ./
    ports:
      - 9090:9090
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=Scalderon4
      - POSTGRES_USER=postgres
      - POSTGRES_DB=taller